### ISSUE TITLE
Change Button Visibility Between Views

### ISSUE THREAD

**Issue by 702573n** [kometenstaub/customizable-page-header-buttons#11]
It would be nice to be able to distinguish buttons not only between mobile and desktop, but also between preview and editor or both.

**Comment by kometenstaub** [comment]
There's not really a good way to implement that, I think.

When a file gets opened, there could be a check for the kind of mode it's in, but that event doesn't get triggered on edit/preview-switches.

I didn't find an event for it in the API, so I'd need to monkey-patch it.

Since this is not something I can implement easily and wouldn't use personally, I probably won't add that feature.
